/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Samuel
 */
public class FrmCamara2 extends javax.swing.JFrame {

    int altoCam;
    int anchoCam;
    BufferedImage ruta1;
    BufferedImage ruta2;
    int contador = 0;

    Webcam webcam;
    WebcamPanel webcamPanel;

    private ImageIcon Img;
    private Icon icono;

    private String codigo;
    private int tipo;
    private JLabel imagen;

    public FrmCamara2(String codigo, JLabel imagen, int tipo) {

        initComponents();

        setTipo(tipo);
        setCodigo(codigo);
        this.setImagen(imagen);

        if (tipo == 2) {
            lblFoto2.setVisible(false);
        }

        this.anchoCam = pnlCam1.getWidth();
        this.altoCam = pnlCam1.getHeight();

        Dimension dimension = new Dimension(anchoCam, altoCam);
        Dimension dimension1 = WebcamResolution.VGA.getSize();
        webcam = Webcam.getDefault();
        webcamPanel = new WebcamPanel(webcam, dimension, false);

        webcam.setViewSize(dimension1);
        webcamPanel.setFitArea(true);
        pnlCam1.setLayout(new FlowLayout());
        pnlCam1.add(webcamPanel);

        iniciarCamara();
    }

    public void iniciarCamara() {
        Thread hilo = new Thread() {
            @Override
            public void run() {
                webcamPanel.start();
            }
        };
        hilo.setDaemon(true);
        hilo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGeneral = new javax.swing.JPanel();
        pnlFoto = new javax.swing.JPanel();
        lblFoto1 = new javax.swing.JLabel();
        lblFoto2 = new javax.swing.JLabel();
        pnlCam = new javax.swing.JPanel();
        pnlCam1 = new javax.swing.JPanel();
        pnlBoton = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnTomar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));

        pnlGeneral.setLayout(new java.awt.GridLayout(2, 0, 0, 10));

        pnlFoto.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        lblFoto1.setBackground(new java.awt.Color(255, 255, 102));
        lblFoto1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblFoto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto1.setText("Anverso");
        lblFoto1.setOpaque(true);
        pnlFoto.add(lblFoto1);

        lblFoto2.setBackground(new java.awt.Color(153, 255, 153));
        lblFoto2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblFoto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFoto2.setText("Reverso");
        lblFoto2.setOpaque(true);
        pnlFoto.add(lblFoto2);

        pnlGeneral.add(pnlFoto);

        pnlCam.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        pnlCam1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlCam1Layout = new javax.swing.GroupLayout(pnlCam1);
        pnlCam1.setLayout(pnlCam1Layout);
        pnlCam1Layout.setHorizontalGroup(
            pnlCam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );
        pnlCam1Layout.setVerticalGroup(
            pnlCam1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 239, Short.MAX_VALUE)
        );

        pnlCam.add(pnlCam1);

        pnlBoton.setLayout(new java.awt.GridLayout(3, 3, 0, 15));
        pnlBoton.add(jLabel1);

        btnTomar.setText("Tomar");
        btnTomar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTomarActionPerformed(evt);
            }
        });
        pnlBoton.add(btnTomar);
        pnlBoton.add(jLabel2);
        pnlBoton.add(jLabel3);

        jButton2.setText("Aceptar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        pnlBoton.add(jButton2);
        pnlBoton.add(jLabel4);
        pnlBoton.add(jLabel5);

        jButton3.setText("jButton3");
        pnlBoton.add(jButton3);
        pnlBoton.add(jLabel6);

        pnlCam.add(pnlBoton);

        pnlGeneral.add(pnlCam);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTomarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTomarActionPerformed
        btnTomar.setText("Tomar Otra");
        //btnAceptar.setEnabled(true);
        ImageIcon foto;
        foto = new ImageIcon(webcam.getImage());
        Icon iconoFoto = new ImageIcon(foto.getImage().getScaledInstance(lblFoto1.getWidth(), lblFoto1.getHeight(), Image.SCALE_SMOOTH));

        if (getTipo() == 2) {
            lblFoto1.setIcon(iconoFoto);
            lblFoto1.setText(null);
            ruta1 = webcam.getImage();
        } else {
            if (lblFoto1.getIcon() == null) {
                lblFoto1.setIcon(iconoFoto);
                lblFoto1.setText(null);
                ruta1 = webcam.getImage();
            } else {
                lblFoto2.setIcon(iconoFoto);
                lblFoto2.setText(null);
                ruta2 = webcam.getImage();
            }
        }


    }//GEN-LAST:event_btnTomarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        guardar();
        webcamPanel.stop();
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void guardar() {

        String rutaImagen;
        String rutaImagen2 = null;
        File salidaimagen = null;
        File salidaimagen2 = null;

        if (getTipo() == 1) {
            rutaImagen = "./src/imagenes/Fotos/Documento/" + getCodigo() + "A.jpg";
            salidaimagen = new File(rutaImagen);
            rutaImagen2 = "./src/imagenes/Fotos/Documento/" + getCodigo() + "R.jpg";
            salidaimagen2 = new File(rutaImagen2);

            try {
                ImageIO.write(ruta1, "jpg", salidaimagen);
                ImageIO.write(ruta2, "jpg", salidaimagen2);
                //JOptionPane.showMessageDialog(null, "Guardado en:" + salidaimagen.getAbsolutePath());
                Img = new ImageIcon(rutaImagen);
                icono = new ImageIcon(Img.getImage().getScaledInstance(154, 200,
                        Image.SCALE_DEFAULT));
                getImagen().setIcon(icono);
            } catch (IOException e) {

                System.out.println("Error " + e);
            }
        }

        rutaImagen = "./src/imagenes/Fotos/U " + getCodigo() + ".jpg";

        lblFoto1.setIcon(null);
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public int getTipo() {
        return tipo;
    }

    public void setTipo(int tipo) {
        this.tipo = tipo;
    }

    public JLabel getImagen() {
        return imagen;
    }

    public void setImagen(JLabel imagen) {
        this.imagen = imagen;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCamara2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCamara2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCamara2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCamara2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrmCamara2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTomar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lblFoto1;
    private javax.swing.JLabel lblFoto2;
    private javax.swing.JPanel pnlBoton;
    private javax.swing.JPanel pnlCam;
    private javax.swing.JPanel pnlCam1;
    private javax.swing.JPanel pnlFoto;
    private javax.swing.JPanel pnlGeneral;
    // End of variables declaration//GEN-END:variables
}
