/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Clases.ClsConnect;
import clases.ClsFunciones;
import clases.ClsPDF;
import clases.ClsVisitante;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel
 */
public class FrmOperadorRecep extends javax.swing.JFrame {

    /**
     * Creates new form FrmOperadorRecep
     */
    ClsConnect cn;
    ClsVisitante cv = new ClsVisitante();
    ClsFunciones func = new ClsFunciones();

    private String query = null;
    private JComboBox cmbPrueba = null;
    private String usuario;
    
    Date date = new Date();
    SimpleDateFormat DateFor = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    
    public FrmOperadorRecep(String usuario) {
        initComponents();

        this.usuario = usuario;
        
        llenarCombo(1, this.cbTipoDoc);
        llenarCombo(2, this.cbNac);
    }

    public void llenarCombo(int tabla, JComboBox combo) {
        String item = null;
        String id = null;

        cn = new ClsConnect();
        cn.conexion("proyectofinal", "umg", "1234");

        try {

            switch (tabla) {
                case 1:
                    this.setQuery("SELECT * FROM tipo_documento");
                    item = "documento";
                    break;
                case 2:
                    this.setQuery("SELECT CONCAT(pais, ' (', alpha3, ')') AS pais FROM nacionalidad2");
                    item = "pais";
                    break;
            }

            ResultSet rs = cn.select(query);
            combo.removeAllItems();

            while (rs.next()) {
                combo.addItem(rs.getString(item));
            }
        } catch (SQLException ex) {
            Logger.getLogger(FrmOperadorRecep.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblEscudo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblImgUsuario = new javax.swing.JLabel();
        pnlDatos2 = new javax.swing.JPanel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblNombre2 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        lblApellido1 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        lblApellido2 = new javax.swing.JLabel();
        txtApellido2 = new javax.swing.JTextField();
        lblTipoDoc = new javax.swing.JLabel();
        cbTipoDoc = new javax.swing.JComboBox<>();
        lblNoDoc = new javax.swing.JLabel();
        txtNoDoc = new javax.swing.JTextField();
        lblNac = new javax.swing.JLabel();
        cbNac = new javax.swing.JComboBox<>();
        txtCorreo = new javax.swing.JTextField();
        lblTel1 = new javax.swing.JLabel();
        txtTel1 = new javax.swing.JTextField();
        lblNoDoc1 = new javax.swing.JLabel();
        txtNoDoc1 = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblCorreo1 = new javax.swing.JLabel();
        btnFotoDoc = new javax.swing.JButton();
        pnlBotones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1188, 675));
        setResizable(false);

        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlTitulo.setPreferredSize(new java.awt.Dimension(1188, 167));

        lblEscudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/umg.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE VISITANTES");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addComponent(lblEscudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEscudo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblImgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pinwi.png"))); // NOI18N
        lblImgUsuario.setToolTipText("");
        lblImgUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        pnlDatos2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNombre1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblNombre1.setText("Primer Nombre");
        lblNombre1.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 220, 40));
        pnlDatos2.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 220, 40));

        lblNombre2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblNombre2.setText("Segundo Nombre");
        lblNombre2.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 220, 40));
        pnlDatos2.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 80, 220, 40));

        lblApellido1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblApellido1.setText("Primer Apellido");
        lblApellido1.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, 40));
        pnlDatos2.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 220, 40));

        lblApellido2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblApellido2.setText("Segundo Apellido");
        lblApellido2.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, 220, 40));
        pnlDatos2.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 140, 220, 40));

        lblTipoDoc.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTipoDoc.setText("Tipo de documento");
        lblTipoDoc.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 220, 40));

        cbTipoDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlDatos2.add(cbTipoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 220, 40));

        lblNoDoc.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblNoDoc.setText("No. Documento");
        lblNoDoc.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblNoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 220, 40));
        pnlDatos2.add(txtNoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 220, 40));

        lblNac.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblNac.setText("Nacionalidad");
        lblNac.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 220, 40));

        cbNac.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        pnlDatos2.add(cbNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, 220, 40));
        pnlDatos2.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 220, 40));

        lblTel1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblTel1.setText("Numero telefonico");
        lblTel1.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 220, 40));
        pnlDatos2.add(txtTel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 220, 40));

        lblNoDoc1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblNoDoc1.setText("No. Documento");
        lblNoDoc1.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblNoDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 220, 40));
        pnlDatos2.add(txtNoDoc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 220, 40));

        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlDatos2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 100, 40));

        lblCorreo1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblCorreo1.setText("Correo electronico");
        lblCorreo1.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblCorreo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, 220, 40));

        btnFotoDoc.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnFotoDoc.setText("Foto Documento");
        btnFotoDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFotoDocActionPerformed(evt);
            }
        });
        pnlDatos2.add(btnFotoDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 220, 40));

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgUsuario)
                .addGap(10, 10, 10)
                .addComponent(pnlDatos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlDatos2, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(lblImgUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlBotones.setPreferredSize(new java.awt.Dimension(380, 70));
        pnlBotones.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        btnCrear.setText("Registrar");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCrear);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 1176, Short.MAX_VALUE)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(404, Short.MAX_VALUE)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(404, 404, 404))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        String seleccion = null;
        if (this.btnCrear.getText().equals("Registrar")) {
            //System.out.println("Crear nuevo visitante");
            String nombre1 = this.txtNombre1.getText();
            String nombre2 = this.txtNombre2.getText();
            String apellido1 = this.txtApellido1.getText();
            String apellido2 = this.txtApellido2.getText();
            String tipoDoc = this.cbTipoDoc.getSelectedItem().toString();
            String noDoc = this.txtNoDoc.getText();
            String nacionalidad = this.cbNac.getSelectedItem().toString();
            String mail = this.txtCorreo.getText();
            String tel = this.txtTel1.getText();
            String foto = "./src/Images/Fotos/" + noDoc + ".jpg ";
            String fotoA = "./src/Images/Fotos/Documento" + noDoc + "A.jpg ";
            String fotoR = "./src/Images/Fotos/Documento" + noDoc + "R.jpg ";

            cv.nuevoVisitante(nombre1, nombre2, apellido1, apellido2, tipoDoc, noDoc, nacionalidad, mail, tel, foto, fotoA, fotoR);

            func.Clear(pnlDatos2);

            seleccion = cv.mensajeCombo();
            System.out.println("seleccion = " + seleccion);
        } else if (this.btnCrear.getText().equals("Crear Ticket")) {
            //System.out.println("Crear ticket");
            seleccion = cv.mensajeCombo();
            this.txtNombre1.requestFocus();
        }

        System.out.println("DateFor.format(date) " + DateFor.format(date));
        
        func.crearQR(this.txtNoDoc.getText(), " G-" + seleccion, DateFor.format(date));
        
        func.crearCorreo();
        func.enviarCorreo();
        
        func.insertarTicket(seleccion, this.usuario, 1);
                
        ClsPDF clsPDF = new ClsPDF();
        clsPDF.setDocumento(this.txtNoDoc.getText());
        clsPDF.setGestion(seleccion);
        clsPDF.crearPDF();
        
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        cv.buscarVisitante(txtNoDoc1.getText(), this.txtNombre1, this.txtNombre2, this.txtApellido1, this.txtApellido2,
                this.txtNoDoc, this.cbTipoDoc, this.cbNac, this.txtCorreo, this.txtTel1);

        if (!cv.isFlag()) {
            func.Clear(pnlDatos2);
            this.btnCrear.setText("Registrar");
        } else {
            this.btnCrear.setText("Crear Ticket");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnFotoDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFotoDocActionPerformed
        new FrmCamara2(this.txtNoDoc.getText(), new JLabel(), 1).setVisible(true);
    }//GEN-LAST:event_btnFotoDocActionPerformed

    public String getQuery() {
        return query;
    }

    public void setQuery(String query) {
        this.query = query;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOperadorRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOperadorRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOperadorRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOperadorRecep.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new FrmOperadorRecep().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnFotoDoc;
    private javax.swing.JComboBox<String> cbNac;
    private javax.swing.JComboBox<String> cbTipoDoc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblEscudo;
    private javax.swing.JLabel lblImgUsuario;
    private javax.swing.JLabel lblNac;
    private javax.swing.JLabel lblNoDoc;
    private javax.swing.JLabel lblNoDoc1;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblTel1;
    private javax.swing.JLabel lblTipoDoc;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatos2;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtNoDoc;
    private javax.swing.JTextField txtNoDoc1;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JTextField txtTel1;
    // End of variables declaration//GEN-END:variables
}
