/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.awt.Component;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.text.JTextComponent;

//import Clases.ClsConnect;
import clases.ClsUsuario;
import java.awt.Image;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Samuel
 */
public class FrmUsuario extends javax.swing.JFrame {

    /**
     * Creates new form FrmUsuario
     */
    private ImageIcon Img;
    private Icon icono;
    private boolean pressed;

    ClsUsuario user = new ClsUsuario();

    public FrmUsuario() {
        initComponents();
        this.txtCodigo.setText(generarCodigo());
        this.btnBuscar.setVisible(false);
        this.txtPass2.setVisible(false);
        this.lblPass2.setVisible(false);
        this.lblVisible2.setVisible(false);

        Img = new ImageIcon("./src/imagenes/visible.png");
        icono = new ImageIcon(Img.getImage().getScaledInstance(this.lblVisible2.getWidth(), this.lblVisible2.getHeight(), Image.SCALE_DEFAULT));

        this.lblVisible2.setIcon(icono);
        this.lblVisible.setIcon(icono);

    }

    private String generarCodigo() {
        Date date = new Date();
        SimpleDateFormat DateFor = new SimpleDateFormat("yyyyMMddHHmmss");

        return DateFor.format(date);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTitulo = new javax.swing.JPanel();
        lblEscudo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblReloj = new javax.swing.JLabel();
        pnlDatos = new javax.swing.JPanel();
        lblImgUsuario = new javax.swing.JLabel();
        pnlDatos2 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblApellido1 = new javax.swing.JLabel();
        lblFechaNac = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        txtNombre1 = new javax.swing.JTextField();
        txtApellido1 = new javax.swing.JTextField();
        lblNombre2 = new javax.swing.JLabel();
        txtNombre2 = new javax.swing.JTextField();
        lblApellido2 = new javax.swing.JLabel();
        txtApellido2 = new javax.swing.JTextField();
        lblPass1 = new javax.swing.JLabel();
        lblPass2 = new javax.swing.JLabel();
        txtPass2 = new javax.swing.JPasswordField();
        txtPass1 = new javax.swing.JPasswordField();
        btnBuscar = new javax.swing.JButton();
        txtFechaNac = new javax.swing.JFormattedTextField();
        lblVisible2 = new javax.swing.JLabel();
        lblVisible = new javax.swing.JLabel();
        chkUsuario = new javax.swing.JCheckBox();
        pnlBotones = new javax.swing.JPanel();
        btnCrear = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuBuscar = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnBuscar = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlTitulo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblEscudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/umg.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("NUEVO USUARIO");

        lblReloj.setBackground(new java.awt.Color(184, 242, 230));
        lblReloj.setFont(new java.awt.Font("Dubai Medium", 1, 36)); // NOI18N
        lblReloj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReloj.setText("00:00:00");
        lblReloj.setOpaque(true);

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblEscudo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlTituloLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTituloLayout.createSequentialGroup()
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblReloj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEscudo))
                .addContainerGap())
        );

        lblImgUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pinwi.png"))); // NOI18N
        lblImgUsuario.setToolTipText("");
        lblImgUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        pnlDatos2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCodigo.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblCodigo.setText("Código");
        lblCodigo.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 40));

        lblNombre1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblNombre1.setText("Primer Nombre");
        lblNombre1.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 220, 40));

        lblApellido1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblApellido1.setText("Primer Apellido");
        lblApellido1.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 40));

        lblFechaNac.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblFechaNac.setText("Fecha de Nacimiento");
        lblFechaNac.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 220, 40));

        lblUsuario.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblUsuario.setText("Usuario");
        lblUsuario.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, 40));
        pnlDatos2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 220, 40));

        txtCodigo.setEnabled(false);
        txtCodigo.setFocusable(false);
        pnlDatos2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 220, 40));
        pnlDatos2.add(txtNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 220, 40));

        txtApellido1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtApellido1FocusLost(evt);
            }
        });
        pnlDatos2.add(txtApellido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 220, 40));

        lblNombre2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblNombre2.setText("Segundo Nombre");
        lblNombre2.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 220, 40));
        pnlDatos2.add(txtNombre2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 100, 220, 40));

        lblApellido2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblApellido2.setText("Segundo Apellido");
        lblApellido2.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, 220, 40));
        pnlDatos2.add(txtApellido2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 150, 220, 40));

        lblPass1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblPass1.setText("Contraseña");
        lblPass1.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 220, 40));

        lblPass2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        lblPass2.setText("Confirmar Contraseña");
        lblPass2.setPreferredSize(new java.awt.Dimension(57, 32));
        pnlDatos2.add(lblPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 220, 40));
        pnlDatos2.add(txtPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 300, 220, 40));

        txtPass1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPass1KeyPressed(evt);
            }
        });
        pnlDatos2.add(txtPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 250, 220, 40));

        btnBuscar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        pnlDatos2.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 100, 40));

        try {
            txtFechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        pnlDatos2.add(txtFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 220, 40));

        lblVisible2.setText("jLabel1");
        lblVisible2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVisible2MousePressed(evt);
            }
        });
        pnlDatos2.add(lblVisible2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 300, 40, 40));

        lblVisible.setText("jLabel1");
        lblVisible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVisibleMousePressed(evt);
            }
        });
        pnlDatos2.add(lblVisible, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 40, 40));

        chkUsuario.setToolTipText("Marque para sugerir usuario");
        chkUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkUsuarioActionPerformed(evt);
            }
        });
        pnlDatos2.add(chkUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 20, 40));

        javax.swing.GroupLayout pnlDatosLayout = new javax.swing.GroupLayout(pnlDatos);
        pnlDatos.setLayout(pnlDatosLayout);
        pnlDatosLayout.setHorizontalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblImgUsuario)
                .addGap(18, 18, 18)
                .addComponent(pnlDatos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlDatosLayout.setVerticalGroup(
            pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatos2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addGroup(pnlDatosLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblImgUsuario)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlBotones.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrear.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        pnlBotones.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 170, 60));

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        pnlBotones.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 170, 60));

        menuBuscar.setText("Usuario");

        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuBuscar.add(jMenuItem1);

        mnBuscar.setText("Buscar");
        mnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnBuscarActionPerformed(evt);
            }
        });
        menuBuscar.add(mnBuscar);

        jMenuItem2.setText("Asignar Perfiles");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuBuscar.add(jMenuItem2);

        jMenuBar1.add(menuBuscar);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlDatos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnBuscarActionPerformed
        Clear(pnlDatos2);

        this.txtCodigo.setEnabled(true);
        this.txtCodigo.setFocusable(true);
        this.txtCodigo.grabFocus();
        this.btnBuscar.setVisible(true);
        this.lblPass1.setVisible(false);
        this.lblPass2.setVisible(false);
        this.txtPass1.setVisible(false);
        this.txtPass2.setVisible(false);
        this.btnCrear.setText("Actualizar");
    }//GEN-LAST:event_mnBuscarActionPerformed

    private void txtPass1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPass1KeyPressed
        this.txtPass2.setVisible(true);
        this.lblPass2.setVisible(true);
        this.lblVisible2.setVisible(true);
    }//GEN-LAST:event_txtPass1KeyPressed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        Object[] options = {"Sí", "No", "Cancelar"};

        if (this.btnCrear.getText().equals("Crear")) {

            try {
                user.nuevoUsuario(this.txtCodigo.getText(), this.txtNombre1.getText(), this.txtNombre2.getText(), this.txtApellido1.getText(),
                        this.txtApellido2.getText(), this.txtFechaNac.getText(), this.txtUsuario.getText(), String.valueOf(this.txtPass1.getPassword()),
                        String.valueOf(this.txtPass2.getPassword()));
            } catch (SQLException ex) {
                Logger.getLogger(FrmUsuario.class.getName()).log(Level.SEVERE, null, ex);
            }

            if (user.isFlag()) {
                int opc = JOptionPane.showOptionDialog(null, "Desea crear un nuevo usuario?", "Usuario", JOptionPane.YES_NO_CANCEL_OPTION,
                        JOptionPane.QUESTION_MESSAGE, null, options, options[0]);

                switch (opc) {
                    case 0:
                        Clear(pnlDatos2);
                        break;
                    case 1:
                        opc = JOptionPane.showOptionDialog(null, "Desea asignar perfiles al usuario recien creado?", "Perfiles",
                                JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
                        switch (opc) {
                            case 0:
                                new FrmPerfil(this.txtCodigo.getText()).setVisible(true);
                                break;
                            case 1:
                                Clear(pnlDatos2);
                                this.txtCodigo.setText(generarCodigo());
                                break;
                            case 2:
                                this.dispose();
                                break;
                        }
                        break;
                    case 2:
                        this.dispose();
                        break;
                }
            }

        } else if (this.btnCrear.getText().equals("Actualizar")) {
            System.out.println("Actualizar");

            user.actualizarUsuario(this.txtCodigo.getText(), this.txtNombre1.getText(), this.txtNombre2.getText(), this.txtApellido1.getText(),
                    this.txtApellido2.getText(), this.txtFechaNac.getText(), this.txtUsuario.getText(), String.valueOf(this.txtPass1.getPassword()),
                    String.valueOf(this.txtPass2.getPassword()));
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void lblVisible2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisible2MousePressed

        if (!isPressed()) {
            Img = new ImageIcon("./src/imagenes/no_visible.png");
            this.txtPass2.setEchoChar((char) 0);
            setPressed(true);
        } else {
            Img = new ImageIcon("./src/imagenes/visible.png");
            this.txtPass2.setEchoChar('*');
            setPressed(false);
        }

        icono = new ImageIcon(Img.getImage().getScaledInstance(this.lblVisible2.getWidth(), this.lblVisible2.getHeight(), Image.SCALE_DEFAULT));

        this.lblVisible2.setIcon(icono);
    }//GEN-LAST:event_lblVisible2MousePressed

    private void lblVisibleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVisibleMousePressed
        if (!isPressed()) {
            Img = new ImageIcon("./src/imagenes/no_visible.png");
            this.txtPass1.setEchoChar((char) 0);
            setPressed(true);
        } else {
            Img = new ImageIcon("./src/imagenes/visible.png");
            this.txtPass1.setEchoChar('*');
            setPressed(false);
        }

        icono = new ImageIcon(Img.getImage().getScaledInstance(this.lblVisible2.getWidth(), this.lblVisible2.getHeight(), Image.SCALE_DEFAULT));

        this.lblVisible.setIcon(icono);
    }//GEN-LAST:event_lblVisibleMousePressed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        System.out.println("Hola");
        user.buscarUsuario(this.txtCodigo.getText(), this.txtNombre1, this.txtNombre2, this.txtApellido1, this.txtApellido2, this.txtFechaNac,
                this.txtUsuario);
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        String usuario = JOptionPane.showInputDialog("Introduzca el usuario");

        new FrmPerfil(usuario).setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void chkUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkUsuarioActionPerformed
        String usuario = this.txtNombre1.getText().charAt(0) + this.txtApellido1.getText();

        this.txtUsuario.setText(usuario.toLowerCase());

    }//GEN-LAST:event_chkUsuarioActionPerformed

    private void txtApellido1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtApellido1FocusLost
        this.chkUsuario.doClick();
    }//GEN-LAST:event_txtApellido1FocusLost

    public boolean isPressed() {
        return pressed;
    }

    public void setPressed(boolean pressed) {
        this.pressed = pressed;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    public static void Clear(JPanel intFrame) {

        for (Component control : intFrame.getComponents()) {
            if (control instanceof JTextField || control instanceof JTextArea) {
                ((JTextComponent) control).setText(""); //abstract superclass
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JCheckBox chkUsuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblApellido2;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEscudo;
    private javax.swing.JLabel lblFechaNac;
    private javax.swing.JLabel lblImgUsuario;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblNombre2;
    private javax.swing.JLabel lblPass1;
    private javax.swing.JLabel lblPass2;
    private javax.swing.JLabel lblReloj;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblVisible;
    private javax.swing.JLabel lblVisible2;
    private javax.swing.JMenu menuBuscar;
    private javax.swing.JMenuItem mnBuscar;
    private javax.swing.JPanel pnlBotones;
    private javax.swing.JPanel pnlDatos;
    private javax.swing.JPanel pnlDatos2;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtApellido2;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JFormattedTextField txtFechaNac;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtNombre2;
    private javax.swing.JPasswordField txtPass1;
    private javax.swing.JPasswordField txtPass2;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
